import type { ProjectItem } from "./ProjectFilter";

export const PROJECTS: ProjectItem[] = [
  {
    slug: "estructura-metalica-villa-zaita",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Estructura Metálica — Estación Metro Villa Zaita",
      en: "Steel Structure — Villa Zaita Metro Station",
    },
    desc: {
      es: "Instalación de estructura metálica en la estación del Metro de Villa Zaita.",
      en: "Steel structure installation at the Villa Zaita Metro station.",
    },
    location: "Villa Zaita, Panamá",
    year: "2023",
    img: "/images/estructura-metalica/5.jpg",
    gallery: [
      "/images/estructura-metalica/5.jpg",
      "/images/estructura-metalica/6.jpg",
      "/images/estructura-metalica/7.jpg",
      "/images/estructura-metalica/8.jpg",
      "/images/estructura-metalica/9.jpg",
    ],
  },
  {
    slug: "76-sitios-tigo",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "76 Sitios Tigo — Llave en Mano",
      en: "76 Tigo Sites — Turnkey",
    },
    desc: {
      es: "Construcción llave en mano de 76 sitios para la red Tigo de Millicom.",
      en: "Turnkey construction of 76 sites for Millicom's Tigo network.",
    },
    location: "Nacional",
    year: "En ejecución",
    img: "/images/76-sitios-tigo/41.jpg",
    gallery: [
      "/images/76-sitios-tigo/41.jpg",
      "/images/76-sitios-tigo/42.jpg",
      "/images/76-sitios-tigo/43.jpg",
    ],
  },
  {
    slug: "20-sitios-bts-phoenix-tower",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "20 Sitios BTS — Phoenix Tower",
      en: "20 BTS Sites — Phoenix Tower",
    },
    desc: {
      es: "Proyecto llave en mano para la construcción de 20 sitios BTS.",
      en: "Turnkey project for the construction of 20 BTS sites.",
    },
    location: "Panamá",
    year: "En ejecución",
    img: "/images/20-sitios-bts/48.jpg",
    gallery: [
      "/images/20-sitios-bts/48.jpg",
      "/images/20-sitios-bts/49.jpg",
      "/images/20-sitios-bts/50.jpg",
      "/images/20-sitios-bts/51.jpg",
    ],
  },
  {
    slug: "mantenimiento-206-sitios",
    cat: "MAINT",
    tagLabel: "MAINT",
    title: {
      es: "Mantenimiento Preventivo — 206 Sitios",
      en: "Preventive Maintenance — 206 Sites",
    },
    desc: {
      es: "Programa de mantenimiento preventivo a 206 sitios de telecomunicaciones.",
      en: "Preventive maintenance program covering 206 telecom sites.",
    },
    location: "Nacional",
    year: "En ejecución",
    img: "/images/76-sitios-tigo/42.jpg",
  },
  {
    slug: "mantenimiento-113-sitios",
    cat: "MAINT",
    tagLabel: "MAINT",
    title: {
      es: "Mantenimiento Preventivo Semestral — 113 Sitios",
      en: "Semi-annual Preventive Maintenance — 113 Sites",
    },
    desc: {
      es: "Mantenimiento preventivo semestral a 113 sitios de Phoenix Tower International.",
      en: "Semi-annual preventive maintenance for 113 Phoenix Tower sites.",
    },
    location: "Nacional",
    year: "En ejecución",
    img: "/images/20-sitios-bts/49.jpg",
  },
  {
    slug: "ampliacion-anden-cabuya",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Ampliación Andén de Recibo — Cabuya",
      en: "Receiving Dock Expansion — Cabuya",
    },
    desc: {
      es: "Mano de obra y equipos para la ampliación del andén de recibo en planta de Empresas Melo.",
      en: "Labor and equipment for the receiving dock expansion at the Melo plant.",
    },
    location: "Cabuya, Panamá",
    year: "2022 — 2023",
    img: "/images/ampliacion-anden-cabuya/24.jpg",
    gallery: [
      "/images/ampliacion-anden-cabuya/24.jpg",
      "/images/ampliacion-anden-cabuya/26.jpg",
      "/images/ampliacion-anden-cabuya/27.jpg",
    ],
  },
  {
    slug: "pesa-camionera-muelle-16",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Pesa Camionera — Muelle 16, Cristóbal",
      en: "Truck Weighing Station — Pier 16, Cristóbal",
    },
    desc: {
      es: "Construcción de pesa camionera, pavimento y drenajes en la terminal de granos del Muelle 16.",
      en: "Truck weighing station, paving and drainage at Pier 16 grain terminal.",
    },
    location: "Puerto Cristóbal, Colón",
    year: "2022",
    img: "/images/muelle-16/28.jpg",
    gallery: [
      "/images/muelle-16/28.jpg",
      "/images/muelle-16/29.jpg",
      "/images/muelle-16/30.jpg",
    ],
  },
  {
    slug: "datacenter-fusion-claro",
    cat: "DATA",
    tagLabel: "DATA",
    title: {
      es: "Datacenter Fusion Module 2000 — Claro",
      en: "Fusion Module 2000 Datacenter — Claro",
    },
    desc: {
      es: "Adecuación civil e instalación de Datacenter Fusion Module 2000 para Claro Panamá.",
      en: "Civil retrofit and Fusion Module 2000 datacenter installation for Claro Panamá.",
    },
    location: "Ciudad de Panamá",
    year: "2018 — 2019",
    img: "/images/datacenter-fusion/59.jpg",
    gallery: [
      "/images/datacenter-fusion/59.jpg",
      "/images/datacenter-fusion/60.jpg",
      "/images/datacenter-fusion/61.jpg",
    ],
  },
  {
    slug: "postes-mimetizados-jmj",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Postes Mimetizados JMJ — Cinta Costera",
      en: "Camouflaged Poles JMJ — Cinta Costera",
    },
    desc: {
      es: "Diseño y construcción de fundaciones e instalación de postes mimetizados para la JMJ.",
      en: "Foundation design and camouflaged pole installation for World Youth Day.",
    },
    location: "Cinta Costera, Panamá",
    year: "2018 — 2019",
    img: "/images/postes-mimetizados/52.jpg",
    gallery: [
      "/images/postes-mimetizados/52.jpg",
      "/images/postes-mimetizados/53.jpg",
      "/images/postes-mimetizados/54.jpg",
      "/images/postes-mimetizados/55.jpg",
    ],
  },
  {
    slug: "124-sitios-3g-cable-wireless",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "124 Sitios 3G — Cable & Wireless",
      en: "124 3G Sites — Cable & Wireless",
    },
    desc: {
      es: "Construcción de 124 sitios 3G para +Móvil: herrajes, antenas, equipos Ericsson y obra civil.",
      en: "124 3G site builds for +Móvil: hardware, antennas, Ericsson gear and civil works.",
    },
    location: "Nacional",
    year: "2009 — 2013",
    img: "/images/124-sitios-3g/105.jpg",
    gallery: [
      "/images/124-sitios-3g/105.jpg",
      "/images/124-sitios-3g/106.jpg",
      "/images/124-sitios-3g/107.jpg",
      "/images/124-sitios-3g/108.jpg",
      "/images/124-sitios-3g/109.jpg",
      "/images/124-sitios-3g/110.jpg",
    ],
  },
  {
    slug: "116-sitios-cosite-mas-movil",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "116 Sitios COSITE y Expansión — +Móvil",
      en: "116 COSITE & Expansion Sites — +Móvil",
    },
    desc: {
      es: "Sistema de tierra, antenas, radio bases GSM, TMA, fibra óptica y obra civil para 116 sitios.",
      en: "Grounding, antennas, GSM base stations, TMA, fiber optics and civil works on 116 sites.",
    },
    location: "Nacional",
    year: "2008 — 2012",
    img: "/images/116-sitios-cosite/97.jpg",
    gallery: [
      "/images/116-sitios-cosite/97.jpg",
      "/images/116-sitios-cosite/98.jpg",
      "/images/116-sitios-cosite/99.jpg",
      "/images/116-sitios-cosite/100.jpg",
      "/images/116-sitios-cosite/101.jpg",
    ],
  },
  {
    slug: "apartamentos-arsema",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Construcción de Apartamentos — ARSEMA",
      en: "Apartment Building Construction — ARSEMA",
    },
    desc: {
      es: "Construcción de edificio residencial de apartamentos para ARSEMA.",
      en: "Construction of a residential apartment building for ARSEMA.",
    },
    location: "Panamá",
    year: "Junio 2023",
    img: "/images/construccion-de-apartamentos/10.jpg",
    gallery: [
      "/images/construccion-de-apartamentos/10.jpg",
      "/images/construccion-de-apartamentos/11.jpg",
      "/images/construccion-de-apartamentos/12.jpg",
      "/images/construccion-de-apartamentos/13.jpg",
    ],
  },
  {
    slug: "mamposteria-agrosilos-chepo",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Cerramiento en Mampostería — Agrosilos Chepo",
      en: "Masonry Enclosure — Agrosilos Chepo Plant",
    },
    desc: {
      es: "Cerramiento perimetral en mampostería para la planta de Agrosilos en Chepo.",
      en: "Perimeter masonry enclosure at the Agrosilos plant in Chepo.",
    },
    location: "Chepo, Panamá",
    year: "Noviembre 2023",
    img: "/images/mamposteria-en-planta/14.jpg",
    gallery: [
      "/images/mamposteria-en-planta/14.jpg",
      "/images/mamposteria-en-planta/15.jpg",
      "/images/mamposteria-en-planta/16.jpg",
      "/images/mamposteria-en-planta/17.jpg",
    ],
  },
  {
    slug: "plataformas-ac-templo-hosanna",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Plataformas de A/C — Templo Hosanna",
      en: "HVAC Platforms — Hosanna Apostolic Temple",
    },
    desc: {
      es: "Mejoras a las plataformas de aire acondicionado del Templo de la Comunidad Apostólica Hosanna.",
      en: "HVAC platform upgrades at the Hosanna Apostolic Community Temple.",
    },
    location: "Panamá",
    year: "2023",
    img: "/images/templo-comunidad-apostolica/18.jpg",
    gallery: [
      "/images/templo-comunidad-apostolica/18.jpg",
      "/images/templo-comunidad-apostolica/19.jpg",
      "/images/templo-comunidad-apostolica/20.jpg",
      "/images/templo-comunidad-apostolica/21.jpg",
    ],
  },
  {
    slug: "estacion-delta-bique",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Estación de Combustible Delta Bique",
      en: "Delta Bique Fuel Station",
    },
    desc: {
      es: "Construcción de la estación de combustible Delta Bique para Petróleos Delta, S.A.",
      en: "Construction of the Delta Bique fuel station for Petróleos Delta, S.A.",
    },
    location: "Bique, Panamá",
    year: "Octubre 2019",
    img: "/images/delta-bique/32.jpg",
    gallery: ["/images/delta-bique/32.jpg"],
  },
  {
    slug: "calle-acceso-muelle-16",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Calle de Acceso Muelle 16 — Fase 1",
      en: "Pier 16 Access Road — Phase 1",
    },
    desc: {
      es: "Diseño y construcción de la calle de acceso al Muelle 16 (Fase 1) para Telfer Tanks, S.A.",
      en: "Design and construction of the Pier 16 access road (Phase 1) for Telfer Tanks, S.A.",
    },
    location: "Colón, Panamá",
    year: "Diciembre 2018",
    img: "/images/calle-acceso-muelle-16/31.jpg",
    gallery: ["/images/calle-acceso-muelle-16/31.jpg"],
  },
  {
    slug: "edificio-comasa-24-dic",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Edificio COMASA — 24 de Diciembre",
      en: "COMASA Building — 24 de Diciembre",
    },
    desc: {
      es: "Suministro de materiales, equipos y mano de obra para la construcción del edificio COMASA para Empresas Melo, S.A.",
      en: "Material, equipment and labor supply for the COMASA building construction for Empresas Melo, S.A.",
    },
    location: "24 de Diciembre, Panamá",
    year: "—",
    img: "/images/comasa-24-dic/33.jpg",
    gallery: ["/images/comasa-24-dic/33.jpg"],
  },
  {
    slug: "datacenter-howard-cw",
    cat: "DATA",
    tagLabel: "DATA",
    title: {
      es: "International Data Center Howard — II Etapa",
      en: "International Data Center Howard — Phase II",
    },
    desc: {
      es: "Segunda etapa del International Data Center Howard para Cable & Wireless Panamá, S.A.",
      en: "Phase II of the International Data Center Howard for Cable & Wireless Panamá, S.A.",
    },
    location: "Howard, Panamá",
    year: "Octubre 2013",
    img: "/images/data-center-howard-etapa2/34.jpg",
    gallery: ["/images/data-center-howard-etapa2/34.jpg"],
  },
  {
    slug: "workshop-container-reachstackers",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Workshop Reachstackers — Panama Ports Company",
      en: "Reachstackers Workshop — Panama Ports Company",
    },
    desc: {
      es: "Workshop para container reachstackers y empty container handlers para Panama Ports Company, S.A.",
      en: "Workshop for container reachstackers and empty container handlers for Panama Ports Company, S.A.",
    },
    location: "Cristóbal, Colón",
    year: "Noviembre 2013",
    img: "/images/empty-container-handlers/36.jpg",
    gallery: ["/images/empty-container-handlers/36.jpg"],
  },
  {
    slug: "patio-contenedores-a1-b1",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Patio de Contenedores A1 – B1",
      en: "Container Yard A1 – B1",
    },
    desc: {
      es: "Construcción de las secciones A1 y B1 del patio de contenedores para Panama Ports Company, S.A.",
      en: "Construction of sections A1 and B1 of the container yard for Panama Ports Company, S.A.",
    },
    location: "Cristóbal, Colón",
    year: "Noviembre 2012",
    img: "/images/A1–B1-OF-CONTAINER-YARD/37.jpg",
    gallery: ["/images/A1–B1-OF-CONTAINER-YARD/37.jpg"],
  },
  {
    slug: "bases-silos-3500tm",
    cat: "CIVIL",
    tagLabel: "CIVIL",
    title: {
      es: "Cuatro Bases para Silos 3500 TM",
      en: "Four Bases for 3,500 TM Silos",
    },
    desc: {
      es: "Construcción de cuatro bases estructurales para silos de 3500 toneladas métricas para Desarrollo Posicional, S.A.",
      en: "Construction of four structural bases for 3,500-tonne silos for Desarrollo Posicional, S.A.",
    },
    location: "Panamá",
    year: "Mayo 2012",
    img: "/images/cuatro-bases-para-silos/38.jpg",
    gallery: ["/images/cuatro-bases-para-silos/38.jpg"],
  },
  {
    slug: "postes-tigo-millicom",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Postes Tigo — Llave en Mano",
      en: "Tigo Poles — Turnkey",
    },
    desc: {
      es: "Proyecto llave en mano de postes Tigo para Millicom.",
      en: "Turnkey Tigo pole project for Millicom.",
    },
    location: "Panamá",
    year: "2022",
    img: "/images/postes-tigo/44.jpg",
    gallery: [
      "/images/postes-tigo/44.jpg",
      "/images/postes-tigo/45.jpg",
      "/images/postes-tigo/46.jpg",
      "/images/postes-tigo/47.jpg",
    ],
  },
  {
    slug: "postes-radome-panama-pacifico",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Postes Radome 24m — Panamá Pacífico",
      en: "24m Radome Poles — Panamá Pacífico",
    },
    desc: {
      es: "Suministro e instalación de postes tipo Radome de 24 m para dos operadores en Panamá Pacífico (Huawei).",
      en: "Supply and installation of 24 m Radome-type poles for two operators at Panamá Pacífico (Huawei).",
    },
    location: "Panamá Pacífico",
    year: "2019",
    img: "/images/postes-radome-pacifico/56.jpg",
    gallery: [
      "/images/postes-radome-pacifico/56.jpg",
      "/images/postes-radome-pacifico/57.jpg",
      "/images/postes-radome-pacifico/58.jpg",
    ],
  },
  {
    slug: "arcos-carreteros-seguridad",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Arcos Carreteros — Ministerio de Seguridad",
      en: "Highway Arches — Ministry of Security",
    },
    desc: {
      es: "Diseño, construcción, suministro e instalación de arcos carreteros para el Ministerio de Seguridad (Huawei).",
      en: "Design, build, supply and installation of highway arches for the Ministry of Security (Huawei).",
    },
    location: "Panamá",
    year: "2018",
    img: "/images/arcos-carreteros-seguridad/62.jpg",
    gallery: [
      "/images/arcos-carreteros-seguridad/62.jpg",
      "/images/arcos-carreteros-seguridad/63.jpg",
      "/images/arcos-carreteros-seguridad/64.jpg",
    ],
  },
  {
    slug: "postes-metalicos-das-cw",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Postes Metálicos 22 m DAS — Cable & Wireless",
      en: "22 m Metallic Poles DAS — Cable & Wireless",
    },
    desc: {
      es: "Diseño, suministro e instalación de postes metálicos modulares de 22 m para sitios DAS.",
      en: "Design, supply and installation of 22 m modular metallic poles for DAS sites.",
    },
    location: "Panamá",
    year: "2014 — Feb 2015",
    img: "/images/postes-metalicos-sitio-das/65.jpg",
    gallery: [
      "/images/postes-metalicos-sitio-das/65.jpg",
      "/images/postes-metalicos-sitio-das/66.jpg",
      "/images/postes-metalicos-sitio-das/67.jpg",
    ],
  },
  {
    slug: "adecuacion-electrica-postes-cw",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Adecuación Eléctrica y Herrajes — Postes Metálicos",
      en: "Electrical & Hardware Retrofit — Metallic Poles",
    },
    desc: {
      es: "Adecuación eléctrica y de herrajes en postes metálicos para sitios de Cable & Wireless Panamá.",
      en: "Electrical and hardware retrofit on metallic poles for Cable & Wireless Panamá sites.",
    },
    location: "Panamá",
    year: "2014 — Feb 2015",
    img: "/images/adecuacion-electrica-poste-metalico/68.jpg",
    gallery: [
      "/images/adecuacion-electrica-poste-metalico/68.jpg",
      "/images/adecuacion-electrica-poste-metalico/69.jpg",
      "/images/adecuacion-electrica-poste-metalico/70.jpg",
      "/images/adecuacion-electrica-poste-metalico/71.jpg",
      "/images/adecuacion-electrica-poste-metalico/72.jpg",
      "/images/adecuacion-electrica-poste-metalico/73.jpg",
    ],
  },
  {
    slug: "obra-civil-sitios-lte-cw",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Obra Civil y Herrajes — Sitios LTE",
      en: "Civil Works & Hardware — LTE Sites",
    },
    desc: {
      es: "Adecuación eléctrica, obra civil y de herrajes en sitios LTE y expansión para Cable & Wireless Panamá.",
      en: "Electrical, civil and hardware works at LTE and expansion sites for Cable & Wireless Panamá.",
    },
    location: "Panamá",
    year: "2015",
    img: "/images/herrajes-sitios-lte/74.jpg",
    gallery: [
      "/images/herrajes-sitios-lte/74.jpg",
      "/images/herrajes-sitios-lte/75.jpg",
    ],
  },
  {
    slug: "expansion-umts-lte-movistar",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Expansión UMTS 1900 + LTE — Movistar / ZTE",
      en: "UMTS 1900 + LTE Expansion — Movistar / ZTE",
    },
    desc: {
      es: "Reemplazo de antenas, instalación de FS Board y fibra óptica para la red UMTS 1900 + LTE de Telefónica Movistar (ZTE).",
      en: "Antenna swap, FS Board installation and fiber optics for Telefónica Movistar's UMTS 1900 + LTE network (ZTE).",
    },
    location: "Panamá",
    year: "—",
    img: "/images/expansion-umts-1900-lte/76.jpg",
    gallery: [
      "/images/expansion-umts-1900-lte/76.jpg",
      "/images/expansion-umts-1900-lte/77.jpg",
      "/images/expansion-umts-1900-lte/78.jpg",
    ],
  },
  {
    slug: "21-sitios-3g-mas-movil",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "21 Sitios 3G — Sectores Adicionales +Móvil",
      en: "21 3G Sites — Additional Sectors +Móvil",
    },
    desc: {
      es: "Adecuación de herrajes, instalación de sistema 3G/UMTS, swap de antenas, equipos Ericsson RBS 3518, PBC-02 y fibra óptica para 21 sitios.",
      en: "Hardware retrofit, 3G/UMTS install, antenna swap, Ericsson RBS 3518, PBC-02 and fiber optics across 21 sites.",
    },
    location: "Panamá",
    year: "2013 — Feb 2014",
    img: "/images/construccion-21-stios-3g/82.jpg",
    gallery: [
      "/images/construccion-21-stios-3g/79.png",
      "/images/construccion-21-stios-3g/80.png",
      "/images/construccion-21-stios-3g/81.png",
      "/images/construccion-21-stios-3g/82.jpg",
      "/images/construccion-21-stios-3g/83.png",
      "/images/construccion-21-stios-3g/84.png",
    ],
  },
  {
    slug: "adecuaciones-obra-civil-cw",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Adecuaciones Obra Civil, Eléctrica y Herrajes",
      en: "Civil, Electrical and Hardware Retrofits",
    },
    desc: {
      es: "Construcción de bases para equipos, instalación eléctrica, sistema de tierra y herrajes en torre y escalerillas para Cable & Wireless Panamá.",
      en: "Equipment base construction, electrical works, grounding, tower hardware and ladder cable trays for Cable & Wireless Panamá.",
    },
    location: "Panamá",
    year: "—",
    img: "/images/adecuaciones-obra-civil/85.jpg",
    gallery: [
      "/images/adecuaciones-obra-civil/85.jpg",
      "/images/adecuaciones-obra-civil/86.jpg",
      "/images/adecuaciones-obra-civil/87.jpg",
    ],
  },
  {
    slug: "5-sitios-continental-towers",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "5 Sitios Nuevos — Continental Towers",
      en: "5 New Sites — Continental Towers",
    },
    desc: {
      es: "Acondicionamiento de terreno, obra civil e instalación de torres y monopolos de 30 y 40 m, sistema de tierra y eléctrico.",
      en: "Site grading, civil works, 30 m and 40 m towers and monopoles, grounding and electrical install.",
    },
    location: "Panamá",
    year: "—",
    img: "/images/construccion-5-sitios-movil/88.jpg",
    gallery: [
      "/images/construccion-5-sitios-movil/88.jpg",
      "/images/construccion-5-sitios-movil/89.jpg",
      "/images/construccion-5-sitios-movil/90.jpg",
      "/images/construccion-5-sitios-movil/91.jpg",
    ],
  },
  {
    slug: "28-sitios-mas-movil",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "28 Sitios Nuevos — +Móvil",
      en: "28 New Sites — +Móvil",
    },
    desc: {
      es: "Torres triangulares y monopolo, sistema de tierra, antenas, radio bases GSM, TMA, feeders, fibra óptica y alarmas en 28 sitios outdoor.",
      en: "Triangular towers and monopole, grounding, antennas, GSM base stations, TMA, feeders, fiber optics and alarms across 28 outdoor sites.",
    },
    location: "Panamá",
    year: "2009 — 2013",
    img: "/images/construccion-28-sitios-mas-movil/92.jpg",
    gallery: [
      "/images/construccion-28-sitios-mas-movil/92.jpg",
      "/images/construccion-28-sitios-mas-movil/93.jpg",
      "/images/construccion-28-sitios-mas-movil/94.jpg",
      "/images/construccion-28-sitios-mas-movil/95.jpg",
    ],
  },
  {
    slug: "planta-externa-mas-digital",
    cat: "TELECOM",
    tagLabel: "TELECOM",
    title: {
      es: "Planta Externa Vertical — 40 Edificios +Digital",
      en: "Vertical Outside Plant — 40 +Digital Buildings",
    },
    desc: {
      es: "Infraestructura vertical y horizontal con tubería PVC, cables coaxiales, conexión al anillo activo y pruebas para 40 edificios +Digital.",
      en: "Vertical and horizontal infrastructure with PVC conduit, coaxial cables, active-ring connection and testing for 40 +Digital buildings.",
    },
    location: "Panamá",
    year: "—",
    img: "/images/construccion-planta-externa/114.jpg",
    gallery: [
      "/images/construccion-planta-externa/114.jpg",
      "/images/construccion-planta-externa/115.jpg",
      "/images/construccion-planta-externa/116.jpg",
    ],
  },
];
